### ISSUE TITLE
標的物 LineBot Notify

### ISSUE THREAD

**Issue by yillkid** [karina1022/CV-bot#6]
## 描述
- 完成 #5 後
- 辨識確定後，將 label 名稱寫入 line bot 中

## 預期目標
- 機器人確定標的物後，以 line bot 通知 user

**Comment by yillkid** [comment]
1. 把 get_ip 的 line_bot 檔案，搬到 CV-bot
2. 獨立測試 ( python3 xxx.py) --> 發 notify
3. 整合

**Comment by karina1022** [comment]
完成程式碼上傳。
